default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: psql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: heroku_db

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>